### ISSUE TITLE
Any Documentation or Help on Posts and Searches?

### ISSUE THREAD

**Issue by ghost** [sgsunder/python-szurubooru#1]
(Excuse my formatting, just wanted to issue this)

I've been developing a discord python bot that would take attachments and links and upload them to the Szurubooru we are hosting. The Discord bot itself is all setup, however I've been having trouble with pyszuru. I have no idea how to make a post with pyszuru.

I'm not a expert on python but I have noticed there is coding for posts, searches, and post notes. However there's not much documentation on how they work yet. Very much understandable if its not finished/broken at the moment. 

I've been looking and experimenting by replacing the "Tag" part of the line. The image i'm using is for the example as it does the same stuff with URLs.
`pyszuru.Post.new(mybooru, "./test.png", "safe");`
However, I keep getting a error
`AttributeError: 'str' object has no attribute 'token'`

**Comment by sgsunder** [comment]
Yup, this codebase is still very much a work-in-progress :D Not sure when I'll get to properly document it.

To create a post you would need to upload the file first, then use the file token, like this:
```python
token = mybooru.upload_file("./test.png")
my_new_post = pyszuru.Post.new(mybooru, token, "safe")
```

**Comment by ghost** [comment]
Thank you so much ^^
Been spending an hour trying to figure this out.
Quick question, what do you use for a URL if any?

**Comment by ghost** [comment]
ah never mind, I'll close this now. Once again, thank you so much.
