### ISSUE TITLE
All Fields are required for namedtuple.

### ISSUE THREAD

**Issue by johnsonince** [sgsunder/python-szurubooru#3]
https://github.com/sgsunder/python-szurubooru/blob/b892214b95b3e6e3a2f07a589716c77de9ab109f/pyszuru/__init__.py#L62

Simplest fix:
`SearchResult(post=Post(self, x["post"]), distance=x["distance"], exact=False)`

**Comment by sgsunder** [comment]
Fixed, thanks for the help!
