### ISSUE TITLE
_create_api_url() fails for tags containing all '/' characters and has other potential issues

### ISSUE THREAD

**Issue by johnsonince** [sgsunder/python-szurubooru#4]
https://github.com/sgsunder/python-szurubooru/blob/b892214b95b3e6e3a2f07a589716c77de9ab109f/pyszuru/api.py#L109

`.rstrip('/')` here completely deletes '///' as a tag. szurubooru appears to support tags like this if they're submitted with proper url encoding is this even necessary here?

**Comment by sgsunder** [comment]
Fixed, thanks for the help!
