### ISSUE TITLE
Feature request: field selecting

### ISSUE THREAD

**Issue by crying-ibex** [sgsunder/python-szurubooru#7]
Hiya! I've been loving this API interface! :)
It certainly beats my old slapdash implementation…

One thing I have been missing, however, is the ability to use [field selecting](https://github.com/rr-/szurubooru/blob/master/doc/API.md#field-selecting) to speed up queries. Is there any chance this feature could be supported? (Even if it's just for post searches)

I've created a [pull request](https://github.com/sgsunder/python-szurubooru/pull/6) with a very basic implementation of this feature. Also, please forgive my code quality, I am still very much a novice ^^;

Thank you, and keep up the good work!

**Comment by sgsunder** [comment]
hmm, so this API uses lazy loading (The property getters for each Post/Tag, when called, can dynamically fetch the value with a HTTP call if it wasn't fetched already).

Ultimately, what fields that are user selected would not really make a _functional_ difference to the user, but yes, specifying the fields needed could be faster overall.

Having the user specify the exact fields would work, but it could be a bit complicated in that they would need to ensure that the field names are correct beforehand, and may suggest that any missing fields would not be accessible through lazy loading. Instead, we could maybe add a boolean toggle that would fetch either a minimized list of fields or the full list of fields for each post/tag. 

I'll work up a quick implementation, see if that might make more sense.

**Comment by sgsunder** [comment]
Implemented in #8 and 13f410e13181322adb5b8f57565f362484a52f1c
